### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by ziming** [alperenersoy/filament-export#1]
Hi,

Thanks for the great package, am wondering if you can tag a 1.0 or 0.x release on github so we can use it.

**Comment by alperenersoy** [comment]
> Hi,
> 
> Thanks for the great package, am wondering if you can tag a 1.0 or 0.x release on github so we can use it.

Hey,

Thanks for your good feedback. I was planning to release it but there is a problem with filtering columns related to the multiselect field. I couldn't figure out the problem yet and didn't want to release something broken. I guess something is wrong with [this line](https://github.com/filamentphp/filament/blob/a313516ec1ba5e969cb5a863c0a56bafc57ba910/packages/forms/resources/js/components/select.js#L208) or the getOptionLabelsUsing() below. It somehow resets the state. I'm sharing the video below. If you have any suggestions please share with me.

https://user-images.githubusercontent.com/83382417/178995270-0addafce-c4fd-4df6-8c84-0e9cc7d0aadd.mp4

**Comment by alperenersoy** [comment]
I've replaced the multiselect with checkboxlist and released v0.1.0 as you requested. Checkboxlist seems working laggy but at least working for now.
