### ISSUE TITLE
Forever white screen

### ISSUE THREAD

**Issue by ziming** [alperenersoy/filament-export#10]
Hi,

I tried both bulk export and header export but what I get is a big white box in the middle of my screen forever.

my code is as follow

->headerActions([
                 FilamentExportHeaderAction::make('export'),
             ]);

and for bulk action it is similar except it is FilamentExportBulkAction

My table has 2500 records

**Comment by alperenersoy** [comment]
hey,

it should work for that many records. at what stage are you experiencing this problem?

**Comment by ziming** [comment]
what do you mean by stage?

**Comment by alperenersoy** [comment]
I mean when you click action or while trying to export?

**Comment by ziming** [comment]
when I click on the action with 2000+ records it is a white screen. before it shows me the options

**Comment by alperenersoy** [comment]
have you tried clearing application cache?

**Comment by ziming** [comment]
yes at the end of my deploy script is clearing various kinds of cache

**Comment by alperenersoy** [comment]
sorry for the late response. can it be related to the data types of the model you use in the resource? have you tried with another model?

**Comment by ziming** [comment]
i have uninstalled the package already, but for the model i tried it with previously, i do have a json column to save an api response

so maybe even tho it's just 3000 records, it may lead to more memory being used i guess

**Comment by alperenersoy** [comment]
yes maybe. sorry for bad experience. I'm aware of the problem and working on a performance improvement.

**Comment by ziming** [comment]
no worries!
