### ISSUE TITLE
Server Error when i try to export large data set [10k records ].

### ISSUE THREAD

**Issue by lodekib** [alperenersoy/filament-export#106]
The export does not respond when exporting large data sets. Takes long to respond or even does not respond.

**Comment by perryfaro** [comment]
@lodekib Have you checked your php settings, do you get an error?

**Comment by alperenersoy** [comment]
@amarafiif can you check [max_execution_time](https://www.php.net/manual/tr/info.configuration.php#ini.max-execution-time) and [memory_limit](https://www.php.net/manual/tr/ini.core.php#ini.memory-limit) in your php.ini config? since it does the download synchronously, you need enough time and memory.

**Comment by amarafiif** [comment]
@alperenersoy Thank you for replying. 

The error I experienced was when I displayed all rows of data, then pressed the export action. However, it will run normally if it only displays 5, 10, 25, 50 rows of data in the resource table.

![image](https://github.com/user-attachments/assets/3fcd2fda-3894-402b-95da-ad2335bc4a1f)

**Comment by alperenersoy** [comment]
@amarafiif are you using header action or bulk action?

**Comment by amarafiif** [comment]
@alperenersoy  i'm using a headerAction

my code like this:
      ->headerActions([
                FilamentExportHeaderAction::make('Ekspor')
                    ->disablePdf()
            ]);

**Comment by alperenersoy** [comment]
@amarafiif can you copy paste all query please?

**Comment by amarafiif** [comment]
@alperenersoy this is my code snippet

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->where('partner_id', Auth('partner')->user()->id)
            ->whereHas('event', function ($query) {
                $query->where('is_running', true);
            });
    }
    
        public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('event.name')
                    ->limit(30)
                    ->sortable()
                    ->searchable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('name')
                    ->label('Nama Tiket')
                    ->limit(50)
                    ->sortable()
                    ->searchable(),
                TextColumn::make('description')
                    ->label('Deskripsi Tiket')
                    ->limit(30)
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('price')
                    ->label('Harga')
                    ->money('IDR', true)
                    ->sortable()
                    ->searchable()
                    ->toggleable(isToggledHiddenByDefault: false),
                TextColumn::make('quota')
                    ->label('Kuota')
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: false),
                TextColumn::make('total_sold')
                    ->label('Terjual')
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: false),
                TextColumn::make('revenue')
                    ->label('Pendapatan')
                    ->money('IDR', true)
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: false),
                TextColumn::make('local_tax')
                    ->label('Pajak Hiburan Daerah')
                    ->money('IDR', true)
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('sale_started')
                    ->label('Mulai Penjualan')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('sale_ended')
                    ->label('Selesai Penjualan')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: false),
                TextColumn::make('custom_fields_count')
                    ->label('Formulir Kustom')
                    ->counts('customFields')
                    ->toggleable(isToggledHiddenByDefault: true),
                ToggleColumn::make('is_publish')
                    ->label('Rilis Publik')
                    ->sortable(),
                BadgeColumn::make('selling_status_enum')
                    ->label('Status Penjualan')
                    ->sortable()
                    ->enum([
                        'UPCOMING' => 'Terjadwal',
                        'ONGOING' => 'Tersedia',
                        'SOLDOUT' => 'Kuota Habis',
                        'ENDED' => 'Berakhir',
                    ])
                    ->colors([
                        'secondary',
                        'primary' => 'UPCOMING',
                        'warning' => 'ENDED',
                        'success' => 'ONGOING',
                        'danger' => 'SOLDOUT',
                    ])
                    ->icons([
                        'heroicon-o-calendar' => 'UPCOMING',
                        'heroicon-o-sparkles' => 'ONGOING',
                        'heroicon-o-exclamation' => 'SOLDOUT',
                        'heroicon-o-clock' => 'ENDED',
                    ]),
                TextColumn::make('created_at')
                    ->label('Dibuat Pada')
                    ->dateTime()
                    ->sortable()
                    ->searchable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->label('Diubah Pada')
                    ->dateTime()
                    ->sortable()
                    ->searchable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->defaultSort('sale_ended', 'desc')
            ->filters([
                SelectFilter::make('event')
                    ->relationship('event', 'name', fn(Builder $query) => $query->where('partner_id', Auth('partner')->User()->id)->where('is_running', true)->orderBy('name'))
                    ->searchable(),
                TernaryFilter::make('is_publish')->label('Publish?')->indicator('Published'),
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make()
                    ->before(function (Tables\Actions\DeleteAction $action, $record) {
                        $hasRestrictedTransaction = $record->transactions()
                            ->whereIn('status', ['PAID', 'PENDING', 'WAITING-PAYMENT'])
                            ->exists();

                        if ($hasRestrictedTransaction) {
                            Notification::make()
                                ->title('Gagal menghapus!')
                                ->body('Yah, tiket ini tidak dapat kamu hapus karena sudah ada yang checkout nih. 😢')
                                ->danger()
                                ->send();

                            $action->cancel();
                        } else {
                            if ($record->customFields()->exists()) {
                                $record->customFields()->detach();
                            }
                        }
                    })
                    ->after(function ($record) {
                        $record->delete();
                    }),
            ])
            ->bulkActions([
                //
            ])
            ->headerActions([
                FilamentExportHeaderAction::make('Ekspor')
                    ->disablePdf()
            ]);
    }

**Comment by amarafiif** [comment]
@alperenersoy 

Illuminate\Database\QueryException

PHP 8.3.10
10.48.25

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'offset 0' at line 1

```
select
  `tickets`.*,
  (
    select
      count(*)
    from
      `custom_fields`
      inner join `custom_field_tickets` on `custom_fields`.`id` = `custom_field_tickets`.`custom_field_id`
    where
      `tickets`.`id` = `custom_field_tickets`.`ticket_id`
  ) as `custom_fields_count`,
  (
    select
      count(*)
    from
      `custom_fields`
      inner join `custom_field_tickets` on `custom_fields`.`id` = `custom_field_tickets`.`custom_field_id`
    where
      `tickets`.`id` = `custom_field_tickets`.`ticket_id`
  ) as `custom_fields_count`
from
  `tickets`
where
  `partner_id` = 6
  and exists (
    select
      *
    from
      `events`
    where
      `tickets`.`event_id` = `events`.`id`
      and `is_running` = 1
  )
  and `tickets`.`deleted_at` is null offset 0
```

**Comment by alperenersoy** [comment]
@amarafiif  does direct download like below work for you? if it works, it may be about pagination for preview. which version of filament and this package are you using? it should have been fixed [here](https://github.com/alperenersoy/filament-export/commit/ae95260aff388250b34d625401d278bd5b56e3a2#diff-4daccd2ea00f771406103476f9847e8c9b4603acad47baacd2362a66bc3558cdL79).

```
FilamentExportHeaderAction::make('Ekspor')
     ->disablePdf()
     ->directDownload()
```

**Comment by amarafiif** [comment]
@alperenersoy Thanks for the help, this solution works and is quite helpful for a while without showing the export preview.

**Comment by alperenersoy** [comment]
@amarafiif glad to help but it is not an actual solution in this case 😄 for filament v3 and latest version of export package this should not be an issue. if it is not i suggest updating packages.
