### ISSUE TITLE
[V3 beta] Error with StaticAction::submit()

### ISSUE THREAD

**Issue by dkstudio86** [alperenersoy/filament-export#108]
I have this error:

`Too few arguments to function Filament\Actions\StaticAction::submit(), 0 passed in /var/www/html/vendor/alperenersoy/filament-export/src/Components/TableView.php on line 145 and exactly 1 expected`

My export definition:

FilamentExportHeaderAction::make('Exportar')
                    ->fileName('inscriptos-'.date('Y-m-d_H.i'))
                    ->defaultFormat('xlsx')
                    ->defaultPageOrientation('landscape')
                    ->withHiddenColumns()
                    ->fileNameFieldLabel('Nombre del Archivo')
                    ->formatFieldLabel('Formato')
                    ->disableAdditionalColumns()
                    ->pageOrientationFieldLabel('Orientación de Página')
                    ->filterColumnsFieldLabel('Filtrar columnas')

As a workaround I can add "->form([])" to export definition and the exported file is downloaded but I lost customization.

(Sorry for my english)

**Comment by alwayshopeless** [comment]
https://github.com/alwayshopeless/filament-export

You can use my fork with fix for resolve this problem. Additional info in pull request:
https://github.com/alperenersoy/filament-export/pull/110

**Comment by Jeffrey-Lang** [comment]
Whats the best way to install your version with the fix?

**Comment by alwayshopeless** [comment]
@Jeffrey-Lang I'm so sorry, I committed to the wrong branch, and also with errors, but now I've fixed it.
You can use local repository on your machine or add link to fork in your repositories in composer.json
Example: https://gist.github.com/alwayshopeless/ffc2537b402e77306d9f88f9b3993445

**Comment by Jeffrey-Lang** [comment]
I found a better solution:

Create a component then extend TableView instead of Component
then add the follow function in the component

` public function getExportAction(): StaticAction
    {
        return StaticAction::make('export')
            ->button()
            ->label(__('filament-export::table_view.export_action_label'))
            ->submit("export")
            ->icon(config('filament-export.export_icon'));
    }`

**Comment by helderlj** [comment]
Still no definitive fix?

**Comment by helderlj** [comment]
> @alwayshopeless Whats the best way to install your version with the fix?


You can point to the fixing commit  by:

`"alperenersoy/filament-export": "^v3.0.1-beta#b27b13e1a72d6f42e8329a31cee2c928c08966af",`

**Comment by helderlj** [comment]
You can point to @alwayshopeless PR while it still not merged in:

`"alperenersoy/filament-export": "v3.x-dev#b27b13e1a72d6f42e8329a31cee2c928c08966af",`

**Comment by alperenersoy** [comment]
hey! sorry for the bad experience. just merged it.
