### ISSUE TITLE
export raw values or reformat them (v3 beta)

### ISSUE THREAD

**Issue by shopapps** [alperenersoy/filament-export#113]
Hi, 

(v3 beta) I may be missing something obvious, but how do I format the column data before an export?

in my table, I have some fields that are visually formatted (i.e.. wrapped in HTML) to add badges or are set to display dates in a specific manner.

when I export to CSV I do not want this HTML to appear I just want to export the raw values or optionally reformat them at the point of export, is this possible?

**Comment by alperenersoy** [comment]
hey,

for now, if a column has formatted state we just return the formatted one but it would be nice to have such functionality. maybe we can implement a function like `formatStateUsing(Table $table, Column $column, Model $record, int $index)` and we can then perform different operations for example according to `$column->getName()`. if you can work on this feel free to pr, if not i can work when I am available.

**Comment by shopapps** [comment]
thanks for the quick response...  am running through your source currently to see what goes where and writing some overrides for what I need, once I have my head around that I can look into a pr, but I'm guessing you will be quicker - lol

I was thinking maybe you have a checkbox on the popup modal and possibly a `->returnRawValues()` bool call to optionally "return raw values only"

**Comment by alperenersoy** [comment]
yeah, returning raw values would be easier, but I am not sure it should affect all columns at once. maybe sth like `->raw(['column_name'])` would be better. but i think anyway, it should be configured in the code instead of the ui.

**Comment by shopapps** [comment]
ooh! yeah passing the columns to be raw is a good idea

**Comment by shopapps** [comment]
looks good, great job (much nicer than my attempt - lol).

I quite liked the convenience of just passing the the column name to get the raw value back, but for any others reading this, the way it works now is:

```php
FilamentExportHeaderAction::make('export')->label(__('Export'))
                    ->formatStates([
                        'status' => fn(Model $record) :string => $record->status, // will just return raw value
                        'numbers' => fn(Model $record): string => $record->numbers()->where('status', Number::STATUS_ACTIVE)->count() . ' / ' . $record->numbers()->where('status', Number::STATUS_DISABLED)->count(),
                    ])
                ,
```
