### ISSUE TITLE
Bad Method Call

### ISSUE THREAD

**Issue by eaziweb95** [alperenersoy/filament-export#12]
I meet this error after following the instructions
![methodCall](https://user-images.githubusercontent.com/58070424/181521191-247d3d93-def3-4d6b-85d3-c2b9dccbba74.jpg)

**Comment by alperenersoy** [comment]
the function name must have been changed. let me check. thanks for reporting!

**Comment by alperenersoy** [comment]
Your version is probably before they changed this function's name. I added backward compatibility and released it. You can update the plugin with filament or the plugin only.

**Comment by eaziweb95** [comment]
filament 2.12.31

**Comment by alperenersoy** [comment]
did updating this plugin to latest release solve your problem?
