### ISSUE TITLE
Direct download functionality still shows modal when in `3.0.3-beta`

### ISSUE THREAD

**Issue by wotta** [alperenersoy/filament-export#125]
Good morning!

I've noticed that in the `3.0.3-beta` branch the `directDownload` method doesn't actually allow a direct download anymore.
Been looking through the code but I am uncertain where the logic for the modal is placed. 

Could you help me understand what I can do to fix this? Either in my project or give me some steps to create a PR to fix the issue.

Best regards!

**Comment by perryfaro** [comment]
@wotta I have just made a fix for your issue, hopefully it will be reviewed and processed soon.

**Comment by alperenersoy** [comment]
merged and released for both versions. thanks @perryfaro your help is appreciated. @wotta sorry for the bad experience.

**Comment by wotta** [comment]
First of thanks @perryfaro! I didn't have the time or exact knowledge to fix this so I really appreciate this. And @alperenersoy don't be sorry! We are all developers and things can break, it is really simple😁
Thanks for taking the time to fix the issue, and I will am looking forward for the new releases.

Have a nice day y'all!
