### ISSUE TITLE
Why is header not added as header in XLS ?

### ISSUE THREAD

**Issue by lukasinko** [alperenersoy/filament-export#132]
Why are headers not added as headers (via `->addHeaders(...)`) at https://github.com/alperenersoy/filament-export/blob/main/src/FilamentExport.php#L136 and why is `->noHeaderRow()` enabled ? Is it because of compatibility with CSV ? Would be here some room for distinguishing them so we can set eg. headerStyle via `modifyExcelWriter` ?

**Comment by lukasinko** [comment]
@alperenersoy Could you give me some insight into it ? I would like to implement some way to style the header.

**Comment by alperenersoy** [comment]
Hey @lukasinko, I can't remember fully. If it works that way, you can implement it. It just looks like a workaround. sth like `addHeaders()` with `addHeadersUsing()` or `formatHeaders()` callback would be better to customize.
