### ISSUE TITLE
`FilamentExportHeaderAction` doesn't respect `getTableQuery` method

### ISSUE THREAD

**Issue by cobraprojects** [alperenersoy/filament-export#21]
for example I have changed `getTableQuery` in my list page

```
protected function getTableQuery(): Builder
    {
        if (auth()->user()->isAdmin) {
            return parent::getTableQuery();
        } elseif (auth()->user()->isDoctor) {
            return parent::getTableQuery()
                ->whereIn('page_id', auth()->user()->pages()->pluck('id'));
        } else {
            return parent::getTableQuery()
                ->when(
                    auth()->user()->branch_id,
                    fn ($q) => $q->where('branch_id', auth()->user()->branch_id)
                );
        }
    }
```

the `FilamentExportHeaderAction` exports all of table records

am I missing somthing?

thanks in advance

**Comment by alperenersoy** [comment]
hey! sorry for your bad experience. since [it creates its own query](https://github.com/alperenersoy/filament-export/blob/2238fa537c0b6c972493c745f410a829ec6296ee/src/Actions/FilamentExportHeaderAction.php#L85) this is expected behavior. let me check what I can do about it.

**Comment by alperenersoy** [comment]
it will now check if you've overridden `getEloquentQuery()` in resource or `getTableQuery()` in your list page. but it needs a public function to access so if you will override `getTableQuery()` be sure it's public.
