### ISSUE TITLE
Uncaught ReferenceError: printTable is not defined

### ISSUE THREAD

**Issue by dhruva81** [alperenersoy/filament-export#25]
I am not able to print on clicking print button and getting following error in console.

```
Uncaught ReferenceError: printTable is not defined
```

I am using only filament-forms and filament-table packages.

Please help me.

**Comment by alperenersoy** [comment]
hey! unfortunately, this package is only for the filament admin panel for now. you may use [pxlrbt/filament-excel](https://github.com/pxlrbt/filament-excel) with table builder package.
