### ISSUE TITLE
Export to excel failed if there's null value

### ISSUE THREAD

**Issue by mtsunu** [alperenersoy/filament-export#28]
If there's null value on our data, when exporting data to xls, the excel package (simple-excel / openspout) will throw an exception that is not properly handled. So the export will stuck on loading state.

The fix / workaround is by casting the state on the line below to string.
https://github.com/alperenersoy/filament-export/blob/d128a0c4ee64cb59ce593ac2d772b7eee2abc890/src/FilamentExport.php#L285

```
$item[$column->getName()] = (string)$state; 
```

**Comment by alperenersoy** [comment]
hey! thanks for reporting. could you pr this?

**Comment by mtsunu** [comment]
done.

https://github.com/alperenersoy/filament-export/pull/29

**Comment by alperenersoy** [comment]
thanks! i will tag it.
