### ISSUE TITLE
exporting fields 

### ISSUE THREAD

**Issue by newtec-foggia** [alperenersoy/filament-export#31]
exporting fields (xls/csv/pdf) of a relationship returns null..

Am I wrong or did I miss something in the documentation?

Thanks,

**Comment by alperenersoy** [comment]
hey. thanks for reporting. how do you get relationship field in the columns?

**Comment by newtec-foggia** [comment]
![Cattura](https://user-images.githubusercontent.com/83398776/200345660-31fd16bf-afef-448f-a7bd-ce3d1c2438d9.JPG)

**Comment by alperenersoy** [comment]
yes, there is a problem with relations. but I just see problem in the preview. xslx export looks correct.

**Comment by vdeville** [comment]
Hello ! 
Thanks for your work @alperenersoy , i'v the same problem in the preview, but ok in export
