### ISSUE TITLE
Fail to export / print

### ISSUE THREAD

**Issue by umardy** [alperenersoy/filament-export#33]
Hi, I found issue when using [TextColumn with rowIndex()](https://filamentphp.com/docs/2.x/tables/columns/text#displaying-the-row-index)

The index column is working normally in filament table view. It filled ordered number from $rowLoop. When I export the table using this plugin, and click Preview button, the modal was pop up, all record is normal, but index column show blanks, while export and print button, debugger showing this error:

`Filament\Tables\Columns\TextColumn::Filament\Tables\Columns\{closure}(): Argument #1 ($rowLoop) must be of type stdClass, null given, called in /Users/umar/Projects/myproject/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php on line 36`.

Please help. Thanks.

**Comment by alperenersoy** [comment]
i will check this and let you know when fixed. sorry for late response.
