### ISSUE TITLE
belongsToThrough

### ISSUE THREAD

**Issue by sergioraldana** [alperenersoy/filament-export#36]
It is possible to use belongsToThrough relationship to export table?

**Comment by alperenersoy** [comment]
if you can see the value in the filament table it should work in the export since it just gets the column's state. but I have not tried. will try and let you know. sorry for the late response.

**Comment by sergioraldana** [comment]
> if you can see the value in the filament table it should work in the export since it just gets the column's state. but I have not tried. will try and let you know. sorry for the late response.

Call to undefined relationship [cursoDisponible] on model [App\Models\Actividad] of type [Illuminate\Database\Eloquent\Relations\BelongsTo].


public function cursoDisponible()
    {
        return $this->belongsToThrough(CursoDisponible::class, Unidad::class, null,
            '',
            [Unidad::class => 'unidad_id', CursoDisponible::class => 'curso_disponible_id' ]);
    }
