### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by vdeville** [alperenersoy/filament-export#37]
Hello,

I detect a problem when try to install the package using composer with php 8.2.
I think you can upgrade spatie laravel excel to work, the bundle was updates to use newest version of spout
Thanks

**Comment by vdeville** [comment]
See my PR https://github.com/alperenersoy/filament-export/pull/38 @alperenersoy 
Thanks

**Comment by alperenersoy** [comment]
hey! will check this and merge if there's no problem. thanks for your contribution.
