### ISSUE TITLE
error in multiple field

### ISSUE THREAD

**Issue by PabloAlanis** [alperenersoy/filament-export#43]
Hello, i have a problem when i try to export a textColumn which have multiple values:

  Forms\Components\Select::make('voltaje_prim_trafo')
                      ...
                      ->multiple()
                      ->options([...

  Tables\Columns\TextColumn::make('voltaje_prim_trafo')
                     ..._

the error is next:

htmlspecialchars(): Argument #1 ($string) must be of type string, array given

https://flareapp.io/share/q5Y3erwP#F85

**Comment by alperenersoy** [comment]
thanks for your contribution! will check that asap.
