### ISSUE TITLE
Set default additional columns

### ISSUE THREAD

**Issue by withoutfanfare** [alperenersoy/filament-export#44]
Hi,

Is there a way to set default additional columns please?

Basically I want to export every column on the model, but not sure how to go about it without adding them into the Modal each time I export.

Thanks,
Danny

**Comment by alperenersoy** [comment]
I added it and released in https://github.com/alperenersoy/filament-export/releases/tag/v0.2.4 quickly. You can use it like:

```php
FilamentExportHeaderAction::make('export')
                    ->withColumns([
                        TextColumn::make('your-extra-column'),
                    ]),
```
