### ISSUE TITLE
Aggregate Column Data Not Visible 

### ISSUE THREAD

**Issue by quietwatcher** [alperenersoy/filament-export#46]
Does It support Laravel-Excel View method?

Tables\Columns\TextColumn::make('invoice_items_sum_total')->sum('invoiceItems','total')->label('Bill Amount'),`

**Comment by alperenersoy** [comment]
hey! sorry for the late response. as I see header action works well with aggregate columns but there is a problem with bulk action. I checked and submitted a [pr](https://github.com/filamentphp/filament/pull/6554) to filament to fix this.
