### ISSUE TITLE
Format Values for Export?

### ISSUE THREAD

**Issue by TonyPartridgeR** [alperenersoy/filament-export#49]
I have a few columns I'd like to format from 1 / 0 to Yes / No. What's the best way to achieve this with Filament-export?

**Comment by alperenersoy** [comment]
did you try with adding `getStateUsing()` to columns? since this package gets state by using `getState()` it may work.

https://filamentphp.com/docs/2.x/tables/columns/getting-started#calculated-state

**Comment by TonyPartridgeR** [comment]
That is actually just what passed my mind earlier. I’ll give it a whirl and let you know.
________________________________
