### ISSUE TITLE
I am getting sql error while trying to export all.

### ISSUE THREAD

**Issue by Nuhel** [alperenersoy/filament-export#52]
I am getting this issue while trying to export all data.

Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'offset 0' at line 1

**Comment by Nuhel** [comment]
> that's weird. can you get and share the sql query?

https://gist.github.com/Nuhel/88ce06814f3e77ec5bf9ea9ffd3c883f

This only Occurs with Header Action

**Comment by alperenersoy** [comment]
yeah, header action builds the query itself. can you somehow dump the sql query which has syntax error to understand in which part it gets error? it may be because of the `whereHas` in your query. can you try without that? so if it's the problem, I can check that.

**Comment by fabinou** [comment]
I have the same, and i don't use where as in my queries 👍 
select * from `deduplication_lignes` where `deduplication_lignes`.`id_deduplication` in (2) offset 0

**Comment by fabinou** [comment]
I dit some tries, what i found out , it's that it's come from the 
/alperenersoy/filament-export/src/Actions/FilamentExportHeaderAction.php line 79, if i hard code the paginate value, it's work again :

```php
 $action->paginator($action->getTableQuery()->paginate(100,['*'], 'exportPage'));
 $action->paginator($action->getTableQuery()->paginate($livewire->tableRecordsPerPage, ['*'], 'exportPage'));
```

```php
dd($livewire->tableRecordsPerPage
-1 // vendor/alperenersoy/filament-export/src/Actions/FilamentExportHeaderAction.php:72

```

But i'm discovering livewire right now, i don't really now how to fix this

**Comment by tkerns** [comment]
I ran into this same issue on a site.  I discovered that the issue only presented itself when the user chose to show all records in the table.  If any of the other  options are chosen the download work as normal.

**Comment by alperenersoy** [comment]
@tkerns are you using v2 or v3?

**Comment by tkerns** [comment]
V2. It’s an old site that I should probably upgrade. I just posted in case someone still using v2 had this issue. It was difficult to track down since a user had this error, and I couldn’t replicate. This thread led me in the right direction.

**Comment by alperenersoy** [comment]
@tkerns @Nuhel @fabinou fixed and released in https://github.com/alperenersoy/filament-export/releases/tag/v0.3.13. could you try and give feedback please?

**Comment by tkerns** [comment]
@alperenersoy  your update fixed the problem for me.  Thank you very much!
