### ISSUE TITLE
SQL Server bind issue - chuck request?

### ISSUE THREAD

**Issue by tonypartridge** [alperenersoy/filament-export#53]
Using SQL Server, when selecting 3000 records (All) we get:

SQLSTATE[IMSSP]: Tried to bind parameter number 2101. SQL Server supports a maximum of 2100 parameters. (SQL: select * from

There are two solutions I can see:

1. Don't bind select all, store 'All Selected' type query which removes the tickbox selection part of the query.
2. Chuck the DB query, so from the select call. Chuck them in batches of 1000, this would solve other issues too where they have searched and the results comeback and you select all results.

thoughts?

**Comment by alperenersoy** [comment]
hey! sorry for the late response. did you experience this while using bulk action or header action? if it's bulk action, I guess livewire tries rehydrating data with comma-separated ids in `where in` query. that may cause this problem.
