### ISSUE TITLE
getTableQuery returning nothing when aggregating data

### ISSUE THREAD

**Issue by iambateman** [alperenersoy/filament-export#54]
First of all, this package is fantastic, thanks for making it!

I believe this is related to #21. I've got a table which is just aggregated data.

### Query

```php
public function getTableQuery(): Builder
    {
        return Participantprogramsession::query()
            ->join('participants', 'participantprogramsessions.participant_id', 'participants.id')
            ->where('participantprogramsessions.status', '=', 0)
            ->select(DB::raw('count(participants.tshirt_size) as count, participants.tshirt_size'))
            ->groupBy('participants.tshirt_size');
    }
```

### Data
![screenshot 2](https://user-images.githubusercontent.com/1709997/216442051-6a862d48-c5a2-4c64-aa35-65ae2326aeed.jpg)

### Problem
When I try to export, it returns just the headings "Size" and "Count" but no data. Is there a way to fix this?

P.S. I was able to get it working perfectly using a more "normal" eloquent query.

**Comment by alperenersoy** [comment]
@iambateman hey! there is a known problem with aggregate columns but I could not have time to fix that.  when I fix it I will let you know.

**Comment by jigzstar** [comment]
> First of all, this package is fantastic, thanks for making it!
> 
> I believe this is related to #21. I've got a table which is just aggregated data.
> 
> ### Query
> ```
> public function getTableQuery(): Builder
>     {
>         return Participantprogramsession::query()
>             ->join('participants', 'participantprogramsessions.participant_id', 'participants.id')
>             ->where('participantprogramsessions.status', '=', 0)
>             ->select(DB::raw('count(participants.tshirt_size) as count, participants.tshirt_size'))
>             ->groupBy('participants.tshirt_size');
>     }
> ```
> 
> ### Data
> ![screenshot 2](https://user-images.githubusercontent.com/1709997/216442051-6a862d48-c5a2-4c64-aa35-65ae2326aeed.jpg)
> 
> ### Problem
> When I try to export, it returns just the headings "Size" and "Count" but no data. Is there a way to fix this?
> 
> P.S. I was able to get it working perfectly using a more "normal" eloquent query.
Interesting...

How did you get this to work via "normal" eloquent methods? I have tried using "withSum" and "withCount" but those create a subquery that is not "grouped by", so I'm left with the 
```DB::raw('SUM(contribution_total) as total'),```
 which ends up as $0.00 on export.

**Comment by alperenersoy** [comment]
hey! sorry for the late response. as I see header action works well with aggregate columns but there is a problem with bulk action. I checked and submitted a [pr](https://github.com/filamentphp/filament/pull/6554) to filament to fix this.
