### ISSUE TITLE
docs: README.md on filamentphp.com

### ISSUE THREAD

**Issue by sWalbrun** [alperenersoy/filament-export#59]
First of all, thank you for your plugin. It works really well and has been exactly what I needed several times.

Now to the issue: The docs on the page https://filamentphp.com/plugins/alperenersoy-export are unfortunately relatively old compared to the README.md from Github. I therefore spent some time thinking about how to include the hidden columns, until I realised that the source code for this was already available.

**Comment by alperenersoy** [comment]
oh sorry, just updated. thanks for reporting!
