### ISSUE TITLE
CSV Delimiter

### ISSUE THREAD

**Issue by mvenghaus** [alperenersoy/filament-export#60]
Hey,

it is possible to set the csv delimiter?

**Comment by alperenersoy** [comment]
hey! at the moment, it is not possible. we can add if it's possible. let me check.

**Comment by mvenghaus** [comment]
@alperenersoy that would be nice .. but no rush ;)

**Comment by alperenersoy** [comment]
@mvenghaus hey I could finally work on this. can be used after the release.

**Comment by mvenghaus** [comment]
@alperenersoy thank you very much!
