### ISSUE TITLE
Class "App\Filament\Resources\FilamentExportBulkAction" not found

### ISSUE THREAD

**Issue by kwaliyo** [alperenersoy/filament-export#64]
Class "App\Filament\Resources\FilamentExportBulkAction" not found

Having this error. what am I to import, or how do I solve the issue?

**Comment by alperenersoy** [comment]
hey! try `use AlperenErsoy\FilamentExport\Actions\FilamentExportBulkAction`

**Comment by kwaliyo** [comment]
Sure, I'll give it a try, thanks.

**Comment by kwaliyo** [comment]
Worked
