### ISSUE TITLE
FilamentExportHeaderAction return all data, doesn't respect getTableQuery method

### ISSUE THREAD

**Issue by mdaushi** [alperenersoy/filament-export#65]
the problem is the same as #21 . I have read all the issues but have not found a solution

 ## in get Table query method i use it like this
```js
  public function getTableQuery(): Builder 
    {
        $record = Route::current()->record;
        return PlanKegiatanPengajuanPerjalananDinas::query()
            ->where('pengajuan_perjalanan_dinas_id', $record);
    }
```

## return data table
![image](https://user-images.githubusercontent.com/51962685/227798136-8e6d7f3e-4eee-40e8-9ed1-ef770951ab6b.png)

## but on export the result returns all data
![image](https://user-images.githubusercontent.com/51962685/227798248-82d486bf-5dac-42b0-ad61-2bf735f9df57.png)
![image](https://user-images.githubusercontent.com/51962685/227798269-24910204-4e50-427f-8ff7-134d757b79cb.png)

am I missing somthing?

thanks in advance

**Comment by alperenersoy** [comment]
hey! somehow the changes i've made in #21 were gone. added again and should work well after the release.
