### ISSUE TITLE
Multiple `headerActions` 

### ISSUE THREAD

**Issue by mcfaith9** [alperenersoy/filament-export#66]
It will be good idea to have fully custom multiple header action, i dont know if its already there, but I tried its not working 

```
use AlperenErsoy\FilamentExport\Actions\FilamentExportHeaderAction;

->headerActions([
      FilamentExportHeaderAction::make('Export')->defaultFormat('pdf')->label('Export PDF'),
      FilamentExportHeaderAction::make('Export')->defaultFormat('xlsx')->label('Export Excel'),
      FilamentExportHeaderAction::make('Export')->defaultFormat('csv')->label('Export CSV')
  ])
```

**Comment by alperenersoy** [comment]
hey. thanks for the idea. will check this.

**Comment by mcfaith9** [comment]
> hey. thanks for the idea. will check this.

Hey @alperenersoy, no need for this one, someone pointing this out on discord, I just to make `action name unique`

![image](https://user-images.githubusercontent.com/34260281/228566574-acf102bb-a225-4b21-8b17-4e428b6b3a0a.png)
![image](https://user-images.githubusercontent.com/34260281/228566713-5daada72-905d-4238-9e03-830af8dc6887.png)

**Comment by alperenersoy** [comment]
@mcfaith9 I am glad you solved your problem. thanks.
