### ISSUE TITLE
balank page when try to print and exported pdf  cutting columns

### ISSUE THREAD

**Issue by yasarpatel** [alperenersoy/filament-export#69]
hi when i try to print document    its giving me blank page but on preview its showing all row and col . and when i try to export to pdf some col is cutting off on exported document .

**Comment by underdpt** [comment]
Hello,

I think printing isn't working on Firefox, this is what I get on Firefox:

![imagen](https://github.com/alperenersoy/filament-export/assets/8122137/4bd1c2ca-6fad-45dd-a37b-eae25e2d78d2)

And this on Google Chrome:

![imagen](https://github.com/alperenersoy/filament-export/assets/8122137/d4265383-fbad-4972-8d08-43a4be93c0e4)

In Microsoft Edge it's also working correctly.

**Comment by yasarpatel** [comment]
your welcome sir .
thanks for you time and help
