### ISSUE TITLE
HasMany relationship - export a row for each related model?

### ISSUE THREAD

**Issue by fongd** [alperenersoy/filament-export#70]
I'm building out an order export system using the Filament Admin Panel. My listing table shows orders which have a HasMany relationship to order line items like so:

```
    /**
     * Get the items for the order.
     */
    public function items(): HasMany
    {
        return $this->hasMany(OrderItem::class, 'order_id', 'order_id');
    }
```

I need to be able to export a CSV or XLSX file of the orders along with their related line items, so if an order has 5 related line items, there would be 5 rows for this order in the exported file, with the order data (name, address, email, etc.) being static and only the line item data changing between the rows.

For example, a `RIGHT JOIN` like this would return what I need:

```
SELECT * FROM order_items RIGHT JOIN orders ON order_items.order_id = orders.order_id
```

However, I don't understand if it's possible to decouple/override the query that the exporter is using from the Filament resource, which is using the `Order` model.

Is it possible to do this?

**Comment by alperenersoy** [comment]
You can override eloquent query in your filament resource (see [here](https://filamentphp.com/docs/2.x/admin/resources/getting-started#customizing-the-eloquent-query)) but I think you cannot export or list in filament table those items properly since both works model based.
