### ISSUE TITLE
allow export columns to be sorted

### ISSUE THREAD

**Issue by eelco2k** [alperenersoy/filament-export#92]
have the possibility to sort / arrange the columns in the export.

**Comment by alperenersoy** [comment]
hey, for now there is no option for that. but we can implement this.

**Comment by perryfaro** [comment]
@eelco2k Maybe this change could help you: https://github.com/alperenersoy/filament-export/pull/103, see the example in the merge request.

**Comment by eelco2k** [comment]
Perfect! Thanks for your effort 🙏🏻
