### ISSUE TITLE
Filament v3 support?

### ISSUE THREAD

**Issue by faizananwerali** [alperenersoy/filament-export#95]
Filament v3 has been released. Will you be supporting it?

**Comment by alperenersoy** [comment]
hey, yes I will support v3 but couldn't check yet how it differs.

**Comment by faizananwerali** [comment]
you can check other plugins which has added support for v3

**Comment by andyholmeswonderful** [comment]
This plugin was updated today to work with V3 now it's officially released, hopefully you can see how it's set up. I don't think it's too different - https://filamentphp.com/plugins/bezhansalleh-shield

**Comment by saulens22** [comment]
@alperenersoy I've added a pull request with v3 support. It needs more testing, though. #96

**Comment by socbaysky** [comment]
+1

**Comment by alperenersoy** [comment]
merged the changes by @saulens22 and [released](https://github.com/alperenersoy/filament-export/releases/tag/v3.0.0-beta) it. thanks @saulens22 for their contributions to v3 migration.

**Comment by andyholmeswonderful** [comment]
Great work @saulens22 @alperenersoy 🙌🏻
