### ISSUE TITLE
Header actions must be an instance of Filament\Actions\Action, or Filament\Actions\ActionGroup.

### ISSUE THREAD

**Issue by aiysya** [alperenersoy/filament-export#98]
Header actions must be an instance of Filament\Actions\Action, or Filament\Actions\ActionGroup.

in  version 3.0.0-bate 

  protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
            FilamentExportHeaderAction::make('export'),
        ];
    }

**Comment by alperenersoy** [comment]
@aiysya hey, where did you locate this function? are you trying for the admin panel or the standalone table package?

**Comment by aiysya** [comment]
> 

tks, $table->headerActions([ FilamentExportHeaderAction::make('export') ])   this way is okay.  Previously  it was written in   ListRecords:: getHeaderActions
